language: minimal

services: docker

script:
- docker run -e BUILD_ID=$TRAVIS_BRANCH repairnator/pipeline
- docker cp `docker ps -a --format "{{.Names}}" | head -1`:/root/$TRAVIS_BRANCH result
- zip -r result.zip result
- curl --upload-file trace.txt https://transfer.sh/result.zip
- cat result/*.json



